paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_structures: 
  blocks: 
    values: 
     - label: Simple Column
       value: 
        _id: div_col_1
        title: 
        subtitle: 
        content: 
     - label: Example Block
       value: 
        _id: example_block
        title: 
        subtitle: 
        content: 
data_config: {}
timezone: Etc/UTC
